package com.mandu.reader.data

import android.net.Uri
import android.util.Base64
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.mandu.reader.core.PasswordRequiredException
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

@RunWith(AndroidJUnit4::class)
class PdfPasswordDeviceTest {
    @Test
    fun encryptedPdfRequiresCorrectPasswordOnEverySupportedApi() = runBlocking {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val file = File.createTempFile("password-", ".pdf", context.cacheDir)
        try {
            file.writeBytes(Base64.decode(ENCRYPTED_PDF.filterNot(Char::isWhitespace), Base64.DEFAULT))
            val repository = BookRepository(context)
            val record = repository.importFile(Uri.fromFile(file))

            expectPasswordFailure { repository.open(record).close() }
            expectPasswordFailure { repository.open(record, "wrong-password").close() }
            repository.open(record, "reader-pass").use { book ->
                assertEquals(1, book.publication.units.size)
                val bitmap = book.render(0, 96)
                assertTrue(bitmap.width > 0 && bitmap.height > 0)
            }
            repository.remove(record.id)
        } finally {
            file.delete()
        }
    }

    private suspend fun expectPasswordFailure(block: suspend () -> Unit) {
        var failedCorrectly = false
        try {
            block()
        } catch (_: PasswordRequiredException) {
            failedCorrectly = true
        }
        assertTrue("expected PasswordRequiredException", failedCorrectly)
    }

    /** Original one-page red PDF generated by Ghostscript with user password reader-pass. */
    private companion object {
        const val ENCRYPTED_PDF = """
            JVBERi0xLjcKJcfsj6IKJSVJbnZvY2F0aW9uOiBncyAtcSAtZEJBVENIIC1kTk9QQVVTRSAtc0RFVklDRT1wZGZ3cml0ZSAtc091dHB1dEZpbGU9PyAtc093bmVyUGFzc3dvcmQ9PyAtc1VzZXJQYXNzd29yZD0/IC1kRW5jcnlwdGlvblI9MyAtZEtleUxlbmd0aD0xMjggPyA/CjUgMCBvYmoKPDwvTGVuZ3RoIDYgMCBSL0ZpbHRlciAvRmxhdGVEZWNvZGU+PgpzdHJlYW0KubKJyH2nRNQ5OJ7XcCYt1zVx5ZnQyJAjGOVcrz86MjDa+JVt8ZxlbmRzdHJlYW0KZW5kb2JqCjQgMCBvYmoKPDwvVHlwZS9QYWdlL01lZGlhQm94IFswIDAgNzIgNzJdCi9QYXJlbnQgMyAwIFIKL1Jlc291cmNlczw8L1Byb2NTZXRbL1BERl0KPj4KL0NvbnRlbnRzIDUgMCBSCj4+CmVuZG9iagozIDAgb2JqCjw8IC9UeXBlIC9QYWdlcyAvS2lkcyBbCjQgMCBSCl0gL0NvdW50IDEKPj4KZW5kb2JqCjEgMCBvYmoKPDwvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMyAwIFIKL01ldGFkYXRhIDggMCBSCj4+CmVuZG9iago4IDAgb2JqCjw8L1R5cGUvTWV0YWRhdGEKL1N1YnR5cGUvWE1ML0xlbmd0aCAxMTgzPj5zdHJlYW0KPD94cGFja2V0IGJlZ2luPSfvu78nIGlkPSdXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQnPz4KPD9hZG9iZS14YXAtZmlsdGVycyBlc2M9IkNSTEYiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSdhZG9iZTpuczptZXRhLycgeDp4bXB0az0nWE1QIHRvb2xraXQgMi45LjEtMTMsIGZyYW1ld29yayAxLjYnPgo8cmRmOlJERiB4bWxuczpyZGY9J2h0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMnIHhtbG5zOmlYPSdodHRwOi8vbnMuYWRvYmUuY29tL2lYLzEuMC8nPgo8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczpwZGY9J2h0dHA6Ly9ucy5hZG9iZS5jb20vcGRmLzEuMy8nIHBkZjpQcm9kdWNlcj0nR1BMIEdob3N0c2NyaXB0IDEwLjA0LjAnLz4KPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSdodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvJz48eG1wOk1vZGlmeURhdGU+MjAyNi0wOS0xMVQwMDowNDozNSswODowMDwveG1wOk1vZGlmeURhdGU+Cjx4bXA6Q3JlYXRlRGF0ZT4yMDI2LTA5LTExVDAwOjA0OjM1KzA4OjAwPC94bXA6Q3JlYXRlRGF0ZT4KPHhtcDpDcmVhdG9yVG9vbD5Vbmtub3duQXBwbGljYXRpb248L3htcDpDcmVhdG9yVG9vbD48L3JkZjpEZXNjcmlwdGlvbj4KPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eGFwTU09J2h0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8nIHhhcE1NOkRvY3VtZW50SUQ9J3V1aWQ6ZGRmMjI4ODItZTU0ZC0xMWZjLTAwMDAtZGNjZDI4MTM3ZmE3Jy8+CjxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiIHhtbG5zOmRjPSdodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLycgZGM6Zm9ybWF0PSdhcHBsaWNhdGlvbi9wZGYnPjxkYzp0aXRsZT48cmRmOkFsdD48cmRmOmxpIHhtbDpsYW5nPSd4LWRlZmF1bHQnPlVudGl0bGVkPC9yZGY6bGk+PC9yZGY6QWx0PjwvZGM6dGl0bGU+PC9yZGY6RGVzY3JpcHRpb24+CjwvcmRmOlJERj4KPC94OnhtcG1ldGE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKPD94cGFja2V0IGVuZD0ndyc/PgplbmRzdHJlYW0KZW5kb2JqCjcgMCBvYmoKPDwvRmlsdGVyL0ZsYXRlRGVjb2RlCi9UeXBlL09ialN0bQovTiAyCi9GaXJzdCA4L0xlbmd0aCAxMDI+PnN0cmVhbQrhZ0dvQb9aLmL/GjvfXuBCns4Bk/blnRX1D8EBfAWVKmexeBOZO0JSNTjwTs7cmXinMDhJEM3hNNt9wuEabg9rAZ93jqibB28GT4rr7LdqSa46xlp4v1MshPLbHnof1iGcon+yvTEKZW5kc3RyZWFtCmVuZG9iago5IDAgb2JqCjw8L0ZpbHRlciAvU3RhbmRhcmQgL1YgMiAvTGVuZ3RoIDEyOCAvUiAzIC9QIC00IC9PICioQ6K2G3VFBVO3qDS7ps403hF7p++8yZt5lJaUH+KgIikKL1UgKFKovYzRCHF2AnTr0u8RIN9cKL9OXk51ikFkAE5W//oBCCk+PgplbmRvYmoKMTAgMCBvYmoKPDwKL1R5cGUgL1hSZWYKL1NpemUgMTEKL1Jvb3QgMSAwIFIgL0luZm8gMiAwIFIKL0lEIFs8M0I0QUZCOEYyRTA4ODFDNEVFRkU5MDU2N0Q0MjFFNkM+PDNCNEFGQjhGMkUwODgxQzRFRUZFOTA1NjdENDIxRTZDPl0KL0VuY3J5cHQgOSAwIFIgL0luZGV4IFswIDExIF0KL1cgWzEgMiAyXQovRmlsdGVyIC9GbGF0ZURlY29kZS9MZW5ndGggNTIKPj4Kc3RyZWFtCnicY2Bg+P+fkXELAwMTAzsDIyNjJQOQ5AQSDHMhYgyMbPdBYl+ABPtiIMFhyMAAANNBBq0KZW5kc3RyZWFtCmVuZG9iagpzdGFydHhyZWYKMjA5NwolJUVPRgo=
        """
    }
}
