<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>ShuiMan</AssemblyName>
    <RootNamespace>ShuiMan.Windows</RootNamespace>
    <Version>0.7.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ShuiMan.Core/ShuiMan.Core.csproj" />
    <Resource Include="../../Resources/WaterCover.png" Link="Assets/WaterCover.png" />
    <Resource Include="AppIcon.png" />
  </ItemGroup>
</Project>
